version: "3"
services:
        api:
            container_name: servlet
            restart: always
            build: .
            ports:
                - 1000:8080
            depends_on:
                - db 
   
            entrypoint: ["./entry-point"]
        db:
            container_name: mysql
            image: mysql
            volumes:
                - "/home/mehdilapin/mysql.conf.d:/etc/mysql/conf.d"
            ports: 
                - 3307:3306
            environment:
                MYSQL_ROOT_PASSWORD: "uvmxu624GJK6DXMS@" 
